# Generated by Django 3.0.3 on 2020-04-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponumber', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('personName', models.CharField(max_length=50)),
                ('phoneNumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'sent'), ('recieved', 'recieved'), ('created', 'created')], max_length=50, null=True)),
            ],
        ),
    ]
